### ISSUE TITLE
Disconnected players disappear from party

### ISSUE THREAD

**Issue by Shiick** [isaacKenyon/VALORANT-rank-yoinker#11]
![image](https://user-images.githubusercontent.com/29106689/134584882-e85a5b47-a747-485c-9f12-32aabb4ee329.png)
Stumbled onto this a few days ago, turned out to have the Phoenix disconnected from the game, thus making Kay/O alone in his party. 
Nothing big, just wanted to report that so it's known.
I don't see any possible fix to this, though I didn't try endpoints to see how it looked for that issue.

**Comment by isaacKenyon** [comment]
not sure how this'll be addressed;

bug & wontfix untill further notice

**Comment by OwOHamper** [comment]
nothing I can do on my site, also the party is rn kinda bugged new logic coming soon

**Comment by isaacKenyon** [comment]
due to the nature of presences, if they're offline we can't see it

wontfix :(
