### ISSUE TITLE
Crashes game randomly whenever this is running

### ISSUE THREAD

**Issue by phantomx1999** [isaacKenyon/VALORANT-rank-yoinker#23]
So i was testing this was working fine a few days back but more recently, past 2 days crashes my game saying a critical error has occurred and the process must be terminated after random intervals in game. 

I have tried with both script and the application both cause the same problem. When im not running this im not facing any crashes.

**Comment by phantomx1999** [comment]
Well i have a complete dump but thats over 3.75 GB i cant provide any screenshots unfortunately as my system just hangs after the error occurs

**Comment by isaacKenyon** [comment]
🤨Can you send the singular .txt that vRY generates?
