### ISSUE TITLE
Wrong Version number in 1.252 (Neon Hotfix)

### ISSUE THREAD

**Issue by Vis17** [isaacKenyon/VALORANT-rank-yoinker#43]
This line should have the version number `1.252`

https://github.com/isaacKenyon/VALORANT-rank-yoinker/blob/ff55b821a8c9a51ed25578f485a03dc7775a0584/src/constants.py#L3

At the moment the program shows

```text
New version available! https://github.com/isaacKenyon/VALORANT-rank-yoinker/releases/download/1.252/VALORANT-rank-yoinker.zip
```

on startup, even though I am running this version.

**Comment by isaacKenyon** [comment]
Thanks, just updated that with https://github.com/isaacKenyon/VALORANT-rank-yoinker/commit/d733ad2ad5e19b37bf9b4c4b2394b4570180e076. It won't make that message disappear though.
