### ISSUE TITLE
How to display other languages/special characters?

### ISSUE THREAD

**Issue by twitchplaystrading** [isaacKenyon/VALORANT-rank-yoinker#46]
For example, Japanese or Chinese gets displayed as boxes with question marks. 
![2022-03-25 21_45_54-Window](https://user-images.githubusercontent.com/74666134/160123345-fd11ecf6-8085-44d2-9bb2-cc3ef811cfb0.png)

**Comment by OwOHamper** [comment]
if you copy the boxes into clipboard and copy somewhere else you will be able to see them. You can even somehow include custom characters in cmd not sure how tho.
