### ISSUE TITLE
so even if i download the latest version it keep saying there's new update.

### ISSUE THREAD

**Issue by MaiSan9999** [isaacKenyon/VALORANT-rank-yoinker#47]
![image](https://user-images.githubusercontent.com/89659009/160141058-3ca023bc-fad8-4ec0-8813-dc5ba028d0fd.png)
![image](https://user-images.githubusercontent.com/89659009/160141072-50e85fc4-78fb-437a-9bc9-1d4e91886672.png)

**Comment by isaacKenyon** [comment]
This is a known bug with the lastest release, the version number wasn't updated to match the update. This has been addressed in the latest source.
