### ISSUE TITLE
Japanese or any foreign language name turns to " ? ? ? "

### ISSUE THREAD

**Issue by dslvd** [isaacKenyon/VALORANT-rank-yoinker#51]
![image](https://user-images.githubusercontent.com/80934874/161974091-89a4df34-b6c6-42c6-b542-596442c0b754.png)

**Comment by isaacKenyon** [comment]
This is a limitation of CMD, you would have to use [Windows Terminal](https://www.microsoft.com/en-gb/p/windows-terminal/9n0dx20hk701) to avoid it.
