### ISSUE TITLE
In game names.

### ISSUE THREAD

**Issue by PaulinaSzreder** [isaacKenyon/VALORANT-rank-yoinker#58]
Does your "feature" show in game names even if player don't wish to?

**Comment by D3CRYPT360** [comment]
Well, it's not our fault that the riot's own API shows that data. If you would like an application which does hide the names if a person has streamer mode on but is like vry I would recommend checking out https://waiua.sonel.dev/ .

**Comment by Xanthus58** [comment]
Hey don't mean to butt in here but there's tons of alternatives that may be better suited to your needs @PaulinaSzreder this 
may include but is not limited to. 
https://waiua.sonel.dev/ 
https://tracker.gg/valorant

I highly recommend you try those out

**Comment by Xanthus58** [comment]
I'm not a developer here but I'm not sure if they are going to implement that feature; if its something you would like to see you can offer to make a pull request or fork the application and make your own version with any modifications you want to see. Just make sure that whatever you wish to do falls under the M.I.T License

**Comment by OwOHamper** [comment]
Well if riot provides that data we will show them in the app. If we would hide it people would use more alternatives and believe me even if we would hide it it would not fix the problem, riot need to fix it on their side.
