### ISSUE TITLE
KeyError: 'aresriot.aws-apse2-prod.ap-gp-sydney-1'

### ISSUE THREAD

**Issue by drewkim1995** [isaacKenyon/VALORANT-rank-yoinker#64]
[log-2.txt](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8823134/log-2.txt)
[log-1.txt](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8823135/log-1.txt)
![image](https://user-images.githubusercontent.com/52646640/171615493-960c5af3-0e35-4bce-a69a-58b5f0ae1d33.png)

Got this error today whilst playing comp.
yoinker seems to run whilst in lobby but when I join a comp game, this error occurs. I play on Sydney, Australia servers.

**Comment by D3CRYPT360** [comment]
It seems riot has added new servers today. Currently you can build an exe using the source code or join our discord and check the support channel to download the compiled exe from the source.

**Comment by D3CRYPT360** [comment]
It seems riot has added new servers today. Currently you can build an exe using the source code or you can download this temp from the source. 
[vRY - Temp build.zip](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8823306/vRY.-.Temp.build.zip)

**Comment by drewkim1995** [comment]
> It seems riot has added new servers today. Currently you can build an exe using the source code or you can download this temp build from the source. [vRY - Temp build.zip](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8823306/vRY.-.Temp.build.zip)

Hey thanks for the reply. That works now but it was constantly crashing and throwing an error saying no config found when I had opened it during agent select in Competitive mode.

I haven't looked through your codebase but would it be possible to make yoinker independent of having hard-coded values for the servers?

**Comment by D3CRYPT360** [comment]
We actually have removed hardcoded servers in Commit c211d91bad17b7dd338137aee62f512a06bfbee1. That is why the temp build works because it is now automatically being fetched. The old version which is currently the "Neon Fix" release has the code with the hardcoded values. A new official vRY version  will be released soon!

**Comment by drewkim1995** [comment]
Awesome work!

**Comment by drewkim1995** [comment]
Did you want me to close this one off and make a new issue for the crashing during agent select?

**Comment by D3CRYPT360** [comment]
Yes please
