### ISSUE TITLE
'aresriot.aws-aps1-prod.ap-gp-mumbai-1'

### ISSUE THREAD

**Issue by ThilekS** [isaacKenyon/VALORANT-rank-yoinker#67]
This error pops up as soon as the agent select starts.

**Comment by D3CRYPT360** [comment]
please download the temp build in #66

**Comment by isaacKenyon** [comment]
This is fixed with release [1.26](https://github.com/isaacKenyon/VALORANT-rank-yoinker/releases/tag/1.26).
