### ISSUE TITLE
Funny Thing, Not a BUG

### ISSUE THREAD

**Issue by NameLord** [isaacKenyon/VALORANT-rank-yoinker#71]
Pickle :)
![image](https://user-images.githubusercontent.com/27507408/174460057-b57083ab-5d46-4d46-8c5f-bfca89288c6a.png)

**Comment by OwOHamper** [comment]
prob pickle library

**Comment by D3CRYPT360** [comment]
![Pickle_rick_transparent_edgetrimmed.png](https://user-images.githubusercontent.com/70775520/174460366-b8fb969c-7f00-48dd-a800-bd34f7e4e5bc.png)

**Comment by isaacKenyon** [comment]
cursed issue
