### ISSUE TITLE
Rank yoinker might be bannable starting this act

### ISSUE THREAD

**Issue by SteffenCarlsen** [isaacKenyon/VALORANT-rank-yoinker#73]
According to the announcement [here](https://www.riotgames.com/en/DevRel/valorant-api-launch), using rank yoinker might become bannable. 

> No personal profiles, scouting tools, guides based on individual players, or personalized data of any kind, UNLESS an individual player chooses to share their data. We want players to have ownership of their data, and we don't want to share it if that player doesn't want it shared. What this looks like can take multiple forms, but it will involve a Riot-owned authentication structure we can unlock for you if we believe your application design warrants it.

**Comment by cvaneerden22** [comment]
I can confirm as I was just banned for using the Valorant-rank-yoinker.

**Comment by JonnyBoy2000** [comment]
![ban](https://user-images.githubusercontent.com/22266893/176061837-5aad2c56-6ef6-4e52-9aef-ec416fa8b93f.png)
Can confirm as well, I have also been banned for using this.

**Comment by AdamAlam** [comment]
![image](https://user-images.githubusercontent.com/46464084/176063089-efb55ec7-f1da-48f3-a2fd-a55ae1c219b2.png)
Can confirm, they did an umbrella ban on anyone using this program. I got banned at the same time as @JonnyBoy2000

**Comment by isaacKenyon** [comment]
the software bypassed streamer mode

so if you didnt update to v1.262 (streamer mode compliant) fast enough you got suspended for 7d.
