### ISSUE TITLE
Im pretty sure i have been banned because of this software

### ISSUE THREAD

**Issue by svenhaha** [isaacKenyon/VALORANT-rank-yoinker#74]
![image](https://user-images.githubusercontent.com/108337124/176159697-3474c1eb-50c3-4c95-b8f2-555d714ac812.png)

**Comment by D3CRYPT360** [comment]
the software bypassed streamer mode

so if you didnt update to 1.262 (complied with streamer mode) fast enough you got suspended for 7d.

 this latest version is fully cleared by riot and you will not be sanctioned for it.
