### ISSUE TITLE
Constant Error

### ISSUE THREAD

**Issue by Echoe28** [isaacKenyon/VALORANT-rank-yoinker#79]
"The program has encountered an error. If the problem persists, please reach support with the logs found in (File Location)"

**Comment by OwOHamper** [comment]
**please reach support with the logs found in (File Location)"**

**Comment by Echoe28** [comment]
[log-6.txt](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/9057072/log-6.txt)

**Comment by OwOHamper** [comment]
update to 2.0
