### ISSUE TITLE
riot handing out 1 week suspensions for VRY pre1.262

### ISSUE THREAD

**Issue by RemyFV** [isaacKenyon/VALORANT-rank-yoinker#85]
> your account has been temporarily suspended for prohibited game modification and will be unable to access VALORANT

support answer:

> The investigation our anti-cheat team conducted confirmed that your account has been detected in using 3rd party applications on multiple occasions.
>  
> Using any unauthorized third party programs, including but not limited to "mods", "hacks", "cheats", "scripts", "bots", "trainers", and automation programs, that interact with the Software in any way, for any purpose, including, without limitation, any unauthorized third party programs that intercept, emulate, or redirect any communication between the Software and Riot Games and any unauthorized third party programs that collect information about the Game by reading areas of memory used by the Software to store information.
>  
> We hope you understand, and cease using 3rd party applications in the future.

with streamer mode names hidden maybe the new version will be safe, but I'm not gonna risk it.

I've never changed any game file, never used any other piece of software so I'm pretty sure it's VRY... :/

**Comment by D3CRYPT360** [comment]
Hello, we have talked to some anti cheat devs and they have told us that the new v2.0 is safe to use and they will not hand out suspensions for it. however it is still an use at your own risk. 

if you had used any versions prior to v1.262 then you have gotten a 7 day temp ban
